# Generated by Django 2.2.16 on 2022-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220406_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_approve',
            field=models.UUIDField(null=True),
        ),
    ]
