# Generated by Django 2.2.16 on 2022-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220407_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'администратор'), ('moderator', 'модератор'), ('user', 'пользователь')], max_length=200, null=True),
        ),
    ]
