# Generated by Django 2.2.16 on 2022-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220407_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(through='reviews.Genre_Title', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
